In [1]:
# Создание наборов данных
from sklearn.svm import SVC
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
import mediapipe as mp
import cv2
import time
import numpy as np
import pandas as pd
import os
import math

# Загрузка обучающего набора
data_train = pd.read_csv("dataset_train_mediapipe_short.csv")

# Загрузка тестового набора
data_test = pd.read_csv("dataset_test_mediapipe_short.csv")

In [2]:
# Вычисление угла между двумя прямыми
def angle(x0, y0, x1, y1, x2, y2):
    '''
    if x1-x0!= 0:
        k1 = (y1 - y0) / (x1 - x0)
        if x2-x0!=0:
            k2 = (y2 - y0) / (x2 - x0)
        tg_angle = abs((k1 - k2) / (1 + k1 * k2))
        return math.atan(tg_angle)
    return math.pi/2
    '''
    calc_angle = math.degrees(math.atan2(y2 - y0, x2 - x0) - math.atan2(y1 - y0, x1 - x0))
    if calc_angle < 0:
        calc_angle += 360
    return calc_angle
#print(angle(0, 0, 0, 1, 2, 0))

In [3]:
Angle_mediaPipe = ['RightElbowAngle', 'LeftElbowAngle', 'RightHandAngle', 'LeftHandAngle', 'RightKneeAngle', 'LeftKneeAngle',
                   'RightLegAngle', 'LeftLegAngle', 
                  ]
Key_Points_MediaPipe = ['Nose', 'LeftEyeInnerCorner', 'LeftEye', 'LefEyeOuterCorner', 
              'RightEyeInnerCorner', 'RightEye', 'RightEyeOuterCorner',
              'LeftEar', 'RightEar', 'MouthLeftCorner', 'MouthRightCorner', 'LeftShoulder', 'RightShoulder',
              'LeftElbow', 'RightElbow', 'LeftWrist', 'RightWrist', 'LeftLittleFinger', 'RightLittleFinger',
              'LeftIndexFinger', 'RightIndexFinger', 'LeftThumb', 'RightThumb', 
              'LeftHip', 'RightHip', 'LeftKnee', 'RightKnee', 'LeftAnkle', 'RightAnkle',
              'LeftHeel', 'RightHeel', 'TheIndexFingerOfTheLeftFoot', 'TheIndexFingerOfTheRightFoot'
]

In [4]:
# Создание пустого датафрейма
def init_data(angle_name):
    data = []
    data.append("FileName")
    for p in angle_name:
        data.append(p)
    data.append("target")
    data = pd.DataFrame(columns = data) 
    return data

In [5]:
# Создание датасета каркасных моделей (набора углов и метки - названия позы)
def create_df_angle_pos(angle_name, df, name_file):
    data = init_data(angle_name)
    target = []
    for i in range(len(df)):
        temp = []
        temp += [df.loc[i]['FileName']]
        temp += [angle(df.loc[i]['RightElbow_x'], df.loc[i]['RightElbow_y'], 
                        df.loc[i]['RightShoulder_x'], df.loc[i]['RightShoulder_y'], 
                        df.loc[i]['RightWrist_x'], df.loc[i]['RightWrist_y'])]
        temp += [angle(df.loc[i]['LeftElbow_x'], df.loc[i]['LeftElbow_y'], 
                        df.loc[i]['LeftShoulder_x'], df.loc[i]['LeftShoulder_y'], 
                        df.loc[i]['LeftWrist_x'], df.loc[i]['LeftWrist_y'])] 
        temp += [angle(df.loc[i]['RightShoulder_x'], df.loc[i]['RightShoulder_y'],
                        df.loc[i]['RightElbow_x'], df.loc[i]['RightElbow_y'], 
                        df.loc[i]['RightHip_x'], df.loc[i]['RightHip_y'])]
        temp += [angle(df.loc[i]['LeftShoulder_x'], df.loc[i]['LeftShoulder_y'],
                        df.loc[i]['LeftElbow_x'], df.loc[i]['LeftElbow_y'], 
                        df.loc[i]['LeftHip_x'], df.loc[i]['LeftHip_y'])]
        temp += [angle(df.loc[i]['RightKnee_x'], df.loc[i]['RightKnee_y'],
                        df.loc[i]['RightHip_x'], df.loc[i]['RightHip_y'], 
                        df.loc[i]['RightAnkle_x'], df.loc[i]['RightAnkle_y'])]
        temp += [angle(df.loc[i]['LeftKnee_x'], df.loc[i]['LeftKnee_y'],
                        df.loc[i]['LeftHip_x'], df.loc[i]['LeftHip_y'], 
                        df.loc[i]['LeftAnkle_x'], df.loc[i]['LeftAnkle_y'])]
        temp += [angle(df.loc[i]['RightHip_x'], df.loc[i]['RightHip_y'],
                       df.loc[i]['RightKnee_x'], df.loc[i]['RightKnee_y'],
                       df.loc[i]['RightShoulder_x'], df.loc[i]['RightShoulder_y'])]
        temp += [angle(df.loc[i]['LeftHip_x'], df.loc[i]['LeftHip_y'],
                       df.loc[i]['LeftKnee_x'], df.loc[i]['LeftKnee_y'],
                       df.loc[i]['LeftShoulder_x'], df.loc[i]['LeftShoulder_y'])]
        temp += [df.loc[i]['target']]
        data.loc[i] = temp # Запись в датафрейм

    data.to_csv(name_file) # Запись датафрейма углов в файл
    return data

In [6]:
# Построение датафрейма угловых скелетных моделей обучающего набора
data_tr_angle = create_df_angle_pos(Angle_mediaPipe, data_train, 'dataset_train_mediapipe_angle.csv')

print(data_tr_angle.info())
data_tr_angle.head()

<class 'pandas.core.frame.DataFrame'>
Index: 969 entries, 0 to 968
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FileName         969 non-null    object
 1   RightElbowAngle  969 non-null    float64
 2   LeftElbowAngle   969 non-null    float64
 3   RightHandAngle   969 non-null    float64
 4   LeftHandAngle    969 non-null    float64
 5   RightKneeAngle   969 non-null    float64
 6   LeftKneeAngle    969 non-null    float64
 7   RightLegAngle    969 non-null    float64
 8   LeftLegAngle     969 non-null    float64
 9   target           969 non-null    object
dtypes: float64(8), object(2)
memory usage: 83.3+ KB
None

,FileName,RightElbowAngle,LeftElbowAngle,RightHandAngle,LeftHandAngle,RightKneeAngle,LeftKneeAngle,RightLegAngle,LeftLegAngle,target
0,DATASET/TRAIN/goddess/00000112.jpg,276.759805,93.981235,270.300602,93.949137,107.568295,251.979837,102.873610,257.228664,goddess
1,DATASET/TRAIN/goddess/00000190.jpg,171.838060,179.960316,238.747371,119.608978,104.539655,244.846548,330.777471,23.456256,goddess
2,DATASET/TRAIN/goddess/00000348.jpg,258.627123,112.908696,260.664257,112.612841,107.139875,262.578674,105.372776,270.017628,goddess
3,DATASET/TRAIN/goddess/00000115.jpg,197.168345,157.855401,267.908767,90.567022,96.933162,269.932722,88.201095,273.879729,goddess
4,DATASET/TRAIN/goddess/00000358.jpg,203.622625,349.746858,190.613129,342.358046,150.575618,209.759759,125.374414,237.498138,goddess

In [7]:
# Построение датафрейма угловых скелетных моделей тестового набора
data_te_angle = create_df_angle_pos(Angle_mediaPipe, data_test, 'dataset_test_mediapipe_angle.csv')

print(data_te_angle.info())
data_te_angle.head()

<class 'pandas.core.frame.DataFrame'>
Index: 429 entries, 0 to 428
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FileName         429 non-null    object
 1   RightElbowAngle  429 non-null    float64
 2   LeftElbowAngle   429 non-null    float64
 3   RightHandAngle   429 non-null    float64
 4   LeftHandAngle    429 non-null    float64
 5   RightKneeAngle   429 non-null    float64
 6   LeftKneeAngle    429 non-null    float64
 7   RightLegAngle    429 non-null    float64
 8   LeftLegAngle     429 non-null    float64
 9   target           429 non-null    object
dtypes: float64(8), object(2)
memory usage: 36.9+ KB
None

,FileName,RightElbowAngle,LeftElbowAngle,RightHandAngle,LeftHandAngle,RightKneeAngle,LeftKneeAngle,RightLegAngle,LeftLegAngle,target
0,DATASET/TEST/goddess/00000016.jpg,250.862852,168.211747,214.859862,129.238526,95.339667,183.908941,165.319881,170.021545,goddess
1,DATASET/TEST/goddess/00000057.jpg,269.716088,108.521143,123.499749,83.931262,215.469515,73.180900,343.332294,331.294034,goddess
2,DATASET/TEST/goddess/00000036.jpg,120.819983,79.519104,32.485405,65.362247,307.958460,47.977432,350.081434,357.797272,goddess
3,DATASET/TEST/goddess/00000088.jpg,197.882928,172.604609,16.879414,31.806396,287.110211,343.277251,345.086963,339.570862,goddess
4,DATASET/TEST/goddess/00000050.jpg,2.010275,357.381999,36.090039,53.106876,340.396132,2.737507,7.382634,357.878268,goddess